"use client";

import Head from "next/head";
import { Navbar } from "~/app/_components/common/navbar"
import { useAuth } from "@clerk/nextjs";
import { UserButton, useUser } from "@clerk/clerk-react";
import { api } from "~/trpc/react";
import { Infinite } from "./common/infinite";
import { InfiniteSearch } from "./common/infinitesearch"
import { useSearchParams } from 'next/navigation'

export function Home() {
  const { sessionId, userId, getToken } = useAuth();
  const user = useUser();
  const username = api.profile.getCurrentUser.useQuery().data;

  const searchParams = useSearchParams()
  const searchKey = searchParams.get('search')

  console.log(searchKey)

  if(searchKey !== null && searchKey !== "") {
    return (
      <>
        <Head>
          <title>Search</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="flex flex-col items-center bg-gradient-to-b">
          <div className="w-full sm:w-[500px]">
            <InfiniteSearch key={searchKey}/>
          </div>
          <div className="mb-6">

          </div>
          
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="flex flex-col items-center bg-gradient-to-b">
          <div className="w-full sm:w-[500px]">
            <Infinite />
          </div>
          
        </main>
      </>
    );
  }

  
}
 
